### ISSUE TITLE
References and bibliography

### ISSUE THREAD

**Issue by rpuenter** [ketch/numipedia#5]
Thanks for the tool, it has directed me to a number of methods that I did not know existed. I´m having some trouble however finding references to some methods, specifically the  RK Chebyshev (5,2) and (5,1), the SSPRK(4,2), but just because those are the ones I´m interested in. 

Would you have a refrence list or bibliegraphy that you could upload?

I also leave a reference which describes a class of schemes that modifies the stability region of Chabyshev methods, removing the singularity points on the real axis at the cost of limiting the maximum extent of the stability region. To be honest, I haven´t found a clean way to tranlate them to a Butcher tableau formulation which would be compatible with your current layout and ease implementation, but maybe someone will find it easy.

Essentially Optimal Explicit Runge-Kutta Methods with Application to Hyperbolic-Parabolic Equations. Link https://www.sam.math.ethz.ch/sam_reports/counter/ct.php?file=/sam_reports/reports_final/reports2008/2008-21_fp.pdf

Explicit Stabilized Runge-Kutta Methods. Link: https://www.semanticscholar.org/paper/Explicit-Stabilized-Runge-Kutta-Methods-Synonyms-%2C-Abdulle/f320de2f21662bcfe5d0ac27d90c6a130cb21b1b

**Comment by ketch** [comment]
@rpuenter Thanks; this was just a fun little side project that was never meant to be complete or comprehensive.  Of course, there are hundreds of methods that could be added, and there are even parameterized families (like the RKC methods) with infinitely many members.

 I know both of those papers very well.  The RKC methods here come from [Verwer's 1996 paper](https://www.sciencedirect.com/science/article/pii/S0168927496000220).

You can generate Butcher tableaus for the kind of RKC methods you mention using my [nodepy](https://github.com/ketch/nodepy) package, as follows (from a Python prompt):

```
from nodepy import rk
method1 = rk.RKC1(5,epsilon=0.1)
method2 = rk.RKC2(5,epsilon=0.2)
```

You can specify any number of stages and any value for epsilon; I'm just putting something in as an example.  Keep in mind that the Butcher form is not the best way to implement these methods; they are more efficient and stable if implemented in a certain Shu-Osher form (which is also generated by Nodepy).

If you're interested in methods with specially-designed stability regions, you might also be interested in [this paper of mine](https://msp.org/camcos/2012/7-2/p04.xhtml) and [this package](https://github.com/ketch/RK-opt).

Bibliographic references for methods would be a nice feature, if I ever get back to developing this further.

**Comment by rpuenter** [comment]
Thanks for the quick response, I didn´t expect it from a project that hasn´t been updated in a while. I will certainly take a look at your other tools and read your papers. 

Right know I´m not in the business of designing time integrators, but I´m looking for an explicit integrator with maximum size of the stability region. The order of accuracy is irrelevent, since it will be used for time marching with local time stepping convergence accleration. For trials I have a generic implementation of a butcher tableau, so I can instantiate different methods just specifying the tableau. Admittedly, that is not an efficient implementation, but since it´s an experimental code, I´m looking first for an efficient method. After one can think of improving the implementation. I will try to learn about the Shu-Osher form to see if it´s succeptible te be built generically also, since it will allow me to better understand the literature in scheme design.

In any case, since I´m not finding refs for the Cheby RK (5,1) and I´m writing a paper that uses it, would there be a preferred way of referencing you? Either your numipedia or the nodepy package seem adequate, but let me know.

**Comment by ketch** [comment]
The reference for the method is in my message above. You should cite that.
